name: Run Gradle
description: Sets up Java and runs Gradle
inputs:
  arguments:
    required: true
    description: Gradle arguments
    default: build
  dependency-graph:
    required: false
    description: Whether to enable GitHub Dependency Graph support
    default: disabled
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v4
      id: setup-java
      with:
        distribution: temurin
        java-version: 21
    - uses: gradle/gradle-build-action@v3
      env:
        JAVA_HOME: ${{ steps.setup-gradle-jdk.outputs.path }}
      with:
        dependency-graph: ${{ inputs.dependency-graph }}
        arguments: |
          -Porg.gradle.java.installations.auto-download=false
          ${{ inputs.arguments }}
          --warning-mode all
