name: Run Gradle
description: Sets up Java and runs Gradle
inputs:
  arguments:
    required: true
    description: Gradle arguments
    default: check
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v3
      id: setup-java
      with:
        distribution: temurin
        java-version: 17
    - uses: gradle/gradle-build-action@v2
      env:
        JAVA_HOME: ${{ steps.setup-gradle-jdk.outputs.path }}
      with:
        arguments: |
          -Porg.gradle.java.installations.auto-download=false
          javaToolchains
          ${{ inputs.arguments }}
