name: Run Gradle
description: Runs a Gradle task
inputs:
  arguments:
    description: Gradle arguments for the build.
    required: false
    default: build
  java-version:
    description: The Java version to compile and test with.
    required: false
    default: "21"
  java-distribution:
    description: The Java distribution to use for the build.
    required: false
    default: temurin
  java-early-access:
    description: Whether the Java distribution is early access.
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup-gradle
      id: setup-gradle
      with:
        java-version: ${{ inputs.java-early-access == 'true' && format('{0}-ea', inputs.java-version) || inputs.java-version }}
        java-distribution: ${{ inputs.java-distribution }}
    - name: Run Gradle
      id: gradle-run
      shell: bash
      run: ./gradlew ${{ inputs.arguments }}
