version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: [ "type: dependency-upgrade" ]

  - package-ecosystem: "npm"
    directory: "/documentation"
    schedule:
      interval: "weekly"
    labels: [ "type: task" ]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: [ "type: task" ]

  - package-ecosystem: "github-actions"
    directory: "/.github/actions/setup-gradle"
    schedule:
      interval: "weekly"
    labels: [ "type: task" ]

  - package-ecosystem: "github-actions"
    directory: "/.github/actions/setup-java"
    schedule:
      interval: "weekly"
    labels: [ "type: task" ]
