name: Prepare Gradle
description: Prepares Gradle for a GitHub Action.
inputs:
  java-version:
    description: The Java version to install.
    required: false
    default: "21"
  java-distribution:
    description: The Java distribution to install.
    required: false
    default: temurin
  java-early-access:
    description: Whether the Java distribution is early access.
    required: false
    default: "false"
  java-toolchain:
    description: Whether a Java toolchain should be used.
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup-java
      id: setup-java
      with:
        java-version: ${{ inputs.java-early-access == 'true' && format('{0}-ea', inputs.java-version) || inputs.java-version }}
        java-distribution: ${{ inputs.java-distribution }}
    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v5
      with:
        allow-snapshot-wrappers: true
    - name: Set up Toolchain
      if: ${{ inputs.java-toolchain == 'true' }}
      shell: bash
      run: |
        echo "org.gradle.java.installations.auto-download=false" >> $HOME/.gradle/gradle.properties
        echo "JDK${{ inputs.java-version }}=$JAVA_HOME" >> $GITHUB_ENV
        echo $JAVA_HOME
    - name: Display Java Toolchain Information
      shell: bash
      run: ./gradlew -q javaToolchains
