name: Prepare Gradle
description: Prepares Gradle for a GitHub Action.
inputs:
  java-version:
    description: The Java version to compile and test with.
    required: true
  java-distribution:
    description: The Java distribution to use for the build.
    required: true
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup-java
      id: setup-java
      with:
        java-version: ${{ inputs.java-version }}
        java-distribution: ${{ inputs.java-distribution }}
    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        allow-snapshot-wrappers: true
    - name: Display Java Toolchain Information
      shell: bash
      run: ./gradlew -q javaToolchains
