[versions]
spotless = "8.8.0"

[libraries]
assertj = { module = "org.assertj:assertj-core", version = "3.27.7" }
checkstyle = { module = "com.puppycrawl.tools:checkstyle", version = "13.8.0" }
jacoco = { module = "org.jacoco:org.jacoco.agent", version = "0.8.15" }
jspecify = { module = "org.jspecify:jspecify", version = "1.0.1" }
junit-bom = { module = "org.junit:junit-bom", version = "6.1.2" }
junit-platformLauncher = { module = "org.junit.platform:junit-platform-launcher" }
foojayResolverConvention = { module = "org.gradle.toolchains.foojay-resolver-convention:org.gradle.toolchains.foojay-resolver-convention.gradle.plugin", version = "1.0.0" }
ktlint = { module = "com.pinterest.ktlint:ktlint-cli", version = "1.8.0" }
nmcpSettings = { module = "com.gradleup.nmcp.settings:com.gradleup.nmcp.settings.gradle.plugin", version = "1.6.1" }
palantirJavaFormat = { module = "com.palantir.javaformat:palantir-java-format", version = "2.96.0" }
spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }

[plugins]
build-spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
spotless = { id = "com.diffplug.spotless" }
