name: Main build
description: Sets up JDK and runs Gradle
inputs:
  arguments:
    required: true
    description: Gradle arguments
    default: build -x :documentation:build
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/run-gradle
      with:
        arguments: ${{ inputs.arguments }}
    - name: Upload Build Reports
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
      if: ${{ failure() }}
      with:
        name: build-reports
        path: "**/build/reports/"
