name: Main build
description: Sets up JDK and runs Gradle
inputs:
  arguments:
    required: true
    description: Gradle arguments
    default: build -x :documentation:build
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/run-gradle
      with:
        arguments: ${{ inputs.arguments }}
    - name: Upload Build Reports
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
      if: ${{ failure() }}
      with:
        name: build-reports
        path: "**/build/reports/"
