name: Main build
description: Sets up JDK and runs Gradle
inputs:
  arguments:
    required: true
    description: Gradle arguments
    default: build -x :documentation:build
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/run-gradle
      with:
        arguments: ${{ inputs.arguments }}
    - name: Upload Build Reports
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
      if: ${{ failure() }}
      with:
        name: build-reports
        path: "**/build/reports/"
