name: Main build
description: Sets up Java and runs Gradle
inputs:
  arguments:
    required: true
    description: Gradle arguments
    default: build
  dependency-graph:
    required: false
    description: Whether to enable GitHub Dependency Graph support
    default: disabled
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/run-gradle
      with:
        arguments: ${{ inputs.arguments }}
        dependency-graph: ${{ inputs.dependency-graph }}
