name: Main build
description: Sets up JDK and runs Gradle
inputs:
  arguments:
    required: true
    description: Gradle arguments
    default: build -x :documentation:build
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/run-gradle
      with:
        arguments: ${{ inputs.arguments }}
    - name: Upload Build Reports
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
      if: ${{ failure() }}
      with:
        name: build-reports
        path: "**/build/reports/"
