[[gradle-conventions]]
= Gradle Conventions

The majority of the build logic is contained within `buildSrc`. Many of conventions are based on the conventions from
JUnit, Spring Boot, Spring Framework, Micronaut, and personal opinions gathered from open source and professional work.

The `buildSrc` project is used because it is automatically treated as an
https://docs.gradle.org/current/userguide/composite_builds.html[included build]. This avoids having to create a separate
project and its associated configuration, albeit minimal configuration

[[gradle-conventions.settings]]
== Settings Conventions

There is a single settings conventions plugin located in `gradle/plugins/settings`. This is primarily to apply the
`org.gradle.toolchains.foojay-resolver-convention` plugin which is managed by a
https://docs.gradle.org/current/userguide/version_catalogs.html[version catalog]. Currently, Gradle does not support
utilizing a version catalog for settings as the settings themselves are meant to define a catalog as well.

