name: Snapshot Publication

on:
  workflow_dispatch:

concurrency:
  group: publish-snapshot
  cancel-in-progress: true

jobs:
  publish_snapshot:
    name: Publish Snapshot Artifacts
    runs-on: ubuntu-latest
    if: github.repository == 'ciscoo/gradle-java-template' && github.ref == 'refs/heads/main'
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Publish
        uses: ./.github/actions/run-gradle
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
#        with: TODO: Enable when project is created
#          arguments: publishAllPublicationsToSonatypeSnapshotsRepository -x check
